//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunInMotion.Gif.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gif()
        {
            this.ImageTags = new HashSet<ImageTag>();
        }
    
        public int ImageId { get; set; }
        public int UserId { get; set; }
        public string SourceId { get; set; }
        public string ThumbnailSizeImageUrl { get; set; }
        public string LargeSizeImageUrl { get; set; }
        public string Rating { get; set; }
        public Nullable<int> StarRating { get; set; }
        public Nullable<bool> IsFavourite { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageTag> ImageTags { get; set; }
        public virtual User User { get; set; }
    }
}
