//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunInMotion.Gif.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTag
    {
        public int TagId { get; set; }
        public string Tag { get; set; }
        public int ImageId { get; set; }
    
        public virtual Gif Gif { get; set; }
    }
}
